### ISSUE TITLE
PathResolver' not found

### ISSUE THREAD

**Issue by mpijierro** [php-deal/framework#27]
Hi,

today I tried to install php-deal and I had the following error:

Fatal error: Uncaught Error: Class 'Go\ParserReflection\Instrument\PathResolver' not found in /var/www/html/...../vendor/goaop/parser-reflection/src/ReflectionEngine.php on line 218

I solved it by excluding the vendor folder in the config as it is said here: https://github.com/Codeception/AspectMock/issues/112

I added   'excludePaths' to configuration:
`ContractApplication::getInstance()->init(array(
    'debug'    => true,
    'appDir'   => __DIR__,
    'cacheDir' => __DIR__.'/cache/',
    'excludePaths' => [__DIR__.'/vendor/']
));`

PhpDeal is great!

**Comment by panosru** [comment]
That is happening only when you use `__DIR__` as your `appDir`, which basically means that you use that at the root of your project there where you keep your vendor files and other files which should not be messed with your src since it's a bad practice, nevertheless a `Common Issues` on `README` would be good to have.
